### PR TITLE
fix: Explicit reader specification is required for Windows

### PR DESCRIPTION
**Pull request by stormljor**
The file is not automatically detected as CSV on Windows (due to being a single column?), so I added a manually specified reader.

url-pattern uses the MultiUrl reader, which does not pass the reader parameter on to the underlying url call.

### CODE REVIEW

**Comment by stormljor** [comment]
@mchantry not sure if I need to ping you to have this checked!

**Comment by stormljor** [comment]
The code QA fault wasn't in my code change, but I reformatted the file with black - I can't do much about climetlab no longer supporting Python 3.7

**Review by mchantry — APPROVED** [review]
Thanks for contributing and doing battle with black/isort. It's great to have this working on windows.

**Comment by mchantry** [comment]
Thanks Lars. Appreciate your contribution.

**Comment by stormljor** [comment]
I usually have a pre-commit hook that does the formatting for me, so I forget to run them manually...

**Pull request merged**
